import NextAuth from "next-auth";
import Google from "next-auth/providers/google";
import { createGuest, getGuest } from "./data-service";

const autoConfig = {
  providers: [
    Google({
      clientId: process.env.AUTH_GOOGLE_ID,
      clientSecret: process.env.AUTH_GOOGLE_SECRET,
    }),

    // CAN ALSO ADD SELF AUTH LIKE EMAIL AUTH
  ],
  callbacks: {
    authorized({ auth, request }) {
      return !!auth?.user; //If there is user then return `true` else `false`.
    },
    async signIn({ user, account, profile }) {
      try {
        const existingGuest = await getGuest(user.email);

        if (!existingGuest)
          await createGuest({ email: user.email, fullName: user.name });
        return true;
      } catch (error) {
        return false;
      }
    },
    async session({ session, user }) {
      // Here, we are storing the id generated by supabase to the session.
      const guest = await getGuest(session.user.email);
      session.user.guestId = guest.id;
      return session;
    },
  },
  pages: {
    // Whenever we click on the `Guest area`, which is a protected route, it redirect it to the `/login` page.
    signIn: "/login",
  },
};

export const {
  auth,
  signIn,
  signOut,
  handlers: { GET, POST },
} = NextAuth(autoConfig);
